### ISSUE TITLE
Apostrophe ( ' ) turned into &#x27; in title

### ISSUE THREAD

**Issue by weird-budy** [jocmp/capyreader#1611]
### Steps to Reproduce

On some titles ' breaks. Mostly seen in lemmy feeds

### Expected behavior

Should render '

### Screenshots or screen recording

<img width="720" height="911" alt="Image" src="https://github.com/user-attachments/assets/7e829e2d-bf2c-40a1-affa-f2697c430ccd" />

### Device, Operating system, and app version

I have seen in Android 13 and 14
 app version Capy Reader 2025.12.1180

**Comment by jocmp** [comment]
Hey @weird-budy - this should be fixed starting in [2026.01.1187](https://github.com/jocmp/capyreader/releases/tag/2026.01.1187). Feel free to reopen if you see otherwise.

**Comment by jocmp** [comment]
@weird-budy I added another patch in [2026.02.1189](https://github.com/jocmp/capyreader/releases/tag/2026.02.1189) that should hopefully address this again.

**Comment by weird-budy** [comment]
On 2026.02.1190 issue solved on article title but still exists on feed name. See screenshots 

![Image](https://github.com/user-attachments/assets/8e0c8a77-0a39-4cb2-a0c0-13a938f30358)

![Image](https://github.com/user-attachments/assets/91487727-0545-4ac2-9776-4900a06a70ad)

![Image](https://github.com/user-attachments/assets/7de800dd-bc6b-485a-aca3-cd459527ced7)

![Image](https://github.com/user-attachments/assets/75ae1452-cb99-4ffa-8caa-cfe895f13aba)

**Comment by jocmp** [comment]
@weird-budy Once the feed name is set, Capy doesn't update it just in case you name it something custom. 

You can fix this by long-pressing the feed name in the feed list, hitting "Edit Feed" and renaming it. Let me know if that still doesn't solve it!

<img width="250" alt="Image" src="https://github.com/user-attachments/assets/6f807a3e-15ea-4370-af19-affb2afd1f70" />

**Comment by weird-budy** [comment]
I can manually fix the name. All the other feeds are now working fine except it's foss. 
Turns out it was their fault 😑 
Found in https://itsfoss.com/rss/

![Image](https://github.com/user-attachments/assets/159f0b6a-08e2-4a7b-a00d-b3faec896467)

**Comment by weird-budy** [comment]
I'll try to reach out to them
