### ISSUE TITLE
Repeated crashing while bad mobile connection

### ISSUE THREAD

**Issue by detrophy** [jocmp/capyreader#416]
### Steps to Reproduce

Issue present on: Capy Reader 2024.10.1058

1. open app while on good mobile connection
2. connection degrades
3. Capy Reader tries to load [stuff]
4. It crashes

As soon as the connection gets better, crashing stops.

### Expected behavior

App alerts user of bad connection. App is not crashing.

**Comment by jocmp** [comment]
Thanks for the bug report. Would you be willing to upload your crash logs for this? This is located under Settings > General > Share crash logs.

**Comment by detrophy** [comment]
Hey, sure.
[capy_crash_logs.txt](https://github.com/user-attachments/files/17287774/capy_crash_logs.txt)

**Comment by jocmp** [comment]
thanks @detrophy - looks like some missing error handling around the Feedbin integration. I'll work on a fix.

**Comment by jocmp** [comment]
I pushed a fix for this in the latest version, 2024.10.1059. Please let me know if you're still running into this issue, and thanks again for the bug report.

**Comment by detrophy** [comment]
The app still crashes occasionally on bad network connection.

![capy_crash_logs.txt](https://github.com/user-attachments/files/17485806/capy_crash_logs.txt)

**Comment by jocmp** [comment]
Thanks for the new crashlogs. It looks like a background I didn't consider. I'll take a closer look.

**Comment by jocmp** [comment]
I ran into this issue myself on a flight last week. The problem I'm seeing in the latest crash logs is that it's a timeout reading the feed results. I have another fix to catch errors in the "refresh" code that I'll include in the next build.

**Comment by avagraphique** [comment]
I'm not sure if its related but for some feeds (namely npr.org), opening an article crashes the reader. I've emailed the crash log via your website.

**Comment by jocmp** [comment]
Thanks for the crash log @avagraphique. It looks like this is the same issue as https://github.com/jocmp/capyreader/issues/528 based on the logs. The bug was present in v1075 and v1076 unfortunately.

Upgrading to [2024.11.1077](https://github.com/jocmp/capyreader/releases/tag/2024.11.1077) should have the fix. Please feel free to open up a new issue if you still see issues.
